### ISSUE TITLE
Support CI build without Nix

### ISSUE THREAD

**Issue by makxenov** [NilFoundation/zkEVM-framework#48]
### Motivation
Ensure that CMakeLists are correct and build is working without Nix hacks.
### Tasks
- [x] Support building `assigner` binary without Nix develop
- [x] Configure building and installation of dependencies
- [x] Implement CI job with building and running tests based on pure CMake.
